### ISSUE TITLE
Docker Environment Variables

### ISSUE THREAD

**Issue by itfloater** [netbymatt/ws4kp#41]
Love the work here, was wondering though if you could implement environment variables in the docker implementation?  It would be nice to be able to set location, displays and settings from environment variables to leave only the display on the page.  Maybe even some options to get rid of all of the extra on the page so that it could be utilized in an iframe on another page.  My specific use case I am looking at is to integrate it with Home Assistant for my primary dashboard.

Really appreciate the work you have put in to get it this far, works great!

**Comment by netbymatt** [comment]
Let's discuss if this is actually necessary. Take a look a [Permalinks](https://github.com/netbymatt/ws4kp#sharing-a-permalink-bookmarking). They have the functionality you're asking for, and also flipping on the [Kiosk](https://github.com/netbymatt/ws4kp#kiosk-mode) will take away all of the extra stuff on the page and set the main area to fill the available space.

Then feed the resulting permalink into the iframe source. Worst case, maybe we just need to make a separate iframe parameter (instead of kiosk) that handles the "fill 100% CSS" slightly differently.

I have not tested in an iframe myself but there seems to be success with it from other discussions in here.
