### ISSUE TITLE
Share link broken

### ISSUE THREAD

**Issue by hzm170** [netbymatt/ws4kp#47]
share link ( copy to clipboard ) is not working ; also how can one add the music to the player?

**Comment by netbymatt** [comment]
Can you provide more information on what's not working such as what web browser you're running on and what platform?

Previous disucssion regarding music: https://github.com/netbymatt/ws4kp/issues/43#issuecomment-2107612071

**Comment by ray-frey** [comment]
I think he meant the permalink button. Mine doesn't seem to copy the permalink to the clipboard

**Comment by gmoran1016** [comment]
Also having issues with the permalink button, This error is displayed in the console when the copy permalink button is pressed. (Firefox 127.0.2)
![Screenshot 2024-07-07 175323](https://github.com/netbymatt/ws4kp/assets/29048060/a4b68bb5-3b44-4e42-80b4-e878925d6f22)

**Comment by netbymatt** [comment]
@gmoran1016 Thanks for the screenshot. This problem has had me stumped because MDN was reporting all the current browsers support the clipboard. But your screenshot shows a non-secure address (HTTP). Normally the secure requirement is relaxed for localhost (and 127.0.0.1) but I've learned a lot of users run this in docker or other local server methods and run in to similar problems, such as GPS location lookups.

Since this throws an undefined error I can detect it and just write the URL to the page to be copied manually.
